# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# This file is not intended for end users of the Galaxy BLAST+ tools.
#
# For technical details, see http://travis-ci.org/ and this blog post
# for background,
# http://blastedbio.blogspot.com/2013/09/using-travis-ci-for-testing-galaxy-tools.html

# Galaxy currently only supports Python 2.7
language: python
cache: pip
jobs:
  include:
    - stage: lint
      python: "3.7"
      before_install:
        - "if grep -P '\t' *.rst */*.rst */*/*.rst; then echo 'Tabs are bad, please use four spaces in RST files.'; false; fi"
        - "if grep -P '\t' */*/*.xml; then echo 'Tabs are bad, please use four spaces in XML files.'; false; fi"
        - "if grep -P '\t' */*/.shed.yml; then echo 'Tabs are bad, please use four spaces in shed YAML files.'; false; fi"
        - "if grep -n -r '[[:blank:]]$' *.rst */*.rst */*/*.rst; then echo 'Please remove trailing whitespace in RST files.'; false; fi"
        - "if grep -n -r '[[:blank:]]$' */*/*.xml; then echo 'Please remove trailing whitespace in XML files.'; false; fi"
        - "if grep -n -r '[[:blank:]]$' */*/.shed.yml; then echo 'Please remove trailing whitespace in shed YAML files.'; false; fi"
      install:
        - pip install --upgrade pip setuptools
        - pip install flake8 flake8-blind-except flake8-docstrings flake8-rst-docstrings restructuredtext-lint
        - echo "Using flake8 to check Python code"
        - flake8 .
        - echo "Using restructuredtext-lint to check our RST files"
        - restructuredtext-lint .
        - pip install planemo
      script:
        - echo "Using planemo lint to check for obvious tool errors"
        - planemo shed_lint --tools --fail_level error --ensure_metadata -r ${TRAVIS_BUILD_DIR}
    - stage: test
      python: "3.7"
      env: GALAXY_BRANCH=master
    - stage: test
      python: "3.7"
      env: GALAXY_BRANCH=dev
    - stage: deploy
      before_install:
        - echo "Removing tools we're not testing"
        - for line in $(cat .tt_skip); do rm -rf $line; done
      install:
        - pip install --upgrade pip setuptools
        - pip install planemo
      script:
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then planemo shed_update --shed_target testtoolshed --force_repository_creation --check_diff --shed_key_from_env TTS_KEY -r datatypes/ tools/ packages/ workflows/; true; fi

# Deployment
# ==========
# This is done with the new TravisCI stages feature, see
# https://blog.travis-ci.com/2017-05-11-introducing-build-stages
#
# Assumes you have set $TTS_KEY in the TravisCI interface,
# and that the test stage passed.
#
# As the deploy is run on a new VM, again remove skipped tools.
#
# Note use of "true" after the "planemo shed_update" which is
# a work-around for a Tool Shed administration rights issue, see
# https://github.com/galaxyproject/planemo/issues/543
#
#
# Planemo Lint
# ============
#
# Planemo can be run to check tools separately from Galaxy, and this
# is fast so we do it *before* the slow process of installing Galaxy
# and running the tool tests.
#
# Installing Galaxy
# =================
#
# We define extra datatypes, and therefore install a Galaxy instance
# and add the datatypes to it.
#
#
# Installing Tool Dependencies
# ============================
#
# We also need to install our tool dependencies, e.g. NCBI BLAST+ binaries,
# which we will do manually rather than via a (local) Galaxy Tool Shed.

before_install:
 - pip install --upgrade pip setuptools
 - pip install planemo
 - echo "Removing tools we're not going to test"
 - for line in $(cat .tt_skip); do rm -rf $line; done
 - echo "Fetching Galaxy ${GALAXY_BRANCH} branch..."
 - cd ${TRAVIS_BUILD_DIR}
 - wget https://codeload.github.com/galaxyproject/galaxy/tar.gz/${GALAXY_BRANCH}
 - tar -zxvf ${GALAXY_BRANCH} | tail
 - cd galaxy-${GALAXY_BRANCH}
 - echo biopython >> requirements.txt


# Configuring tools within Galaxy
# ===============================
#
# We setup our datatypes by adding blast.py to the Galaxy library folder,
# and replacing the datatypes_conf.xml file.
#
# Note that as of October 2016, the Galaxy datatypes are back in the
# Galaxy core. Therefore we'll over-write them if needed.

install:
 - cd ${TRAVIS_BUILD_DIR}/galaxy-${GALAXY_BRANCH}
 - bash scripts/common_startup.sh --no-create-venv --dev-wheels


# Testing tools in Galaxy
# =======================
#
# Having setup our Galaxy with our datatypes, and dependencies,
# call planemo test

script:
 - cd ${TRAVIS_BUILD_DIR}
 - planemo --version
 - planemo test --galaxy_root ${TRAVIS_BUILD_DIR}/galaxy-${GALAXY_BRANCH} --skip_venv tools/

notifications:
  email: false
