# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# This file is not intended for end users of the Galaxy BLAST+ tools.
#
# For technical details, see http://travis-ci.org/ and this blog post
# for background,
# http://blastedbio.blogspot.com/2013/09/using-travis-ci-for-testing-galaxy-tools.html


# We need Python 2.6 or 2.7 to run Galaxy (and some of the wrappers)
# but don't really care which. We also need Java to run Blast2GO,
# and perhaps the simplest way to get that installed to to run this
# entire TravisCI build as "java" (which will still have a system
# python installed).
#
language: java

# Installing Galaxy
# =================
#
# Before installing our Galaxy wrappers, we need to install Galaxy.
#
# Galaxy used to be developed in hg using BitBucket, but cloning with
# hg or getting a specific revision with wget was quite slow. Using
# git clone with a mirror on GitHub was faster, while getting the
# latest revision with wget from GitHub was even faster.
#
# We therefore use wget with the new official Galaxy repository on
# GitHub, https://github.com/galaxyproject/galaxy
#
#
# Installing Tool Dependencies
# ============================
#
# We grab Galaxy, and will later make configuration changes specifically
# for testing our tools. Otherwise we use the default settings such as
# running with an SQLite database.
#
# We also need to install our tool dependencies, e.g. NCBI BLAST+ binaries,
# which we will do manually rather than via a (local) Galaxy Tool Shed.
#

before_install:
 - echo "Creating virtual environment (with pip) for Galaxy's Python"
 - sudo apt-get install -y python-virtualenv
 - virtualenv .
 - source bin/activate
 - echo "Fixing permissions on Python eggs cache folder"
 - mkdir -p "$HOME/.python-eggs"
 - chmod 700 "$HOME/.python-eggs" 
 - echo "Fetching and installing Blast2GO for pipelines (b2g4pipe)..."
 - wget http://www.blast2go.com/data/blast2go/b2g4pipe_v2.5.zip
 - unzip b2g4pipe_v2.5.zip
 - cp b2g4pipe/b2gPipe.properties b2g4pipe/Spain_2012_August.properties
 - sed -i "s/Dbacces.dbname=b2g_apr12/Dbacces.dbname=b2g_aug12/g" b2g4pipe/Spain_2012_August.properties
 - sed -i "s/Dbacces.dbhost=10.10.100.203/Dbacces.dbhost=publicdb.blast2go.com/g" b2g4pipe/Spain_2012_August.properties
 - cp b2g4pipe/b2gPipe.properties b2g4pipe/Spain_2011_June.properties
 - sed -i "s/Dbacces.dbname=b2g_apr12/Dbacces.dbname=b2g_jun11/g" b2g4pipe/Spain_2011_June.properties
 - sed -i "s/Dbacces.dbhost=10.10.100.203/Dbacces.dbhost=publicdb.blast2go.com/g" b2g4pipe/Spain_2011_June.properties
 - export B2G4PIPE="${TRAVIS_BUILD_DIR}/b2g4pipe/"
 - echo "Fetching and installing NCBI BLAST+..."
 - wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.30/ncbi-blast-2.2.30+-x64-linux.tar.gz
 - tar -zxvf ncbi-blast-2.2.30+-x64-linux.tar.gz | tail
 - export PATH="${TRAVIS_BUILD_DIR}/ncbi-blast-2.2.30+/bin:$PATH"
 - echo "Fetching Galaxy..."
 - wget https://codeload.github.com/galaxyproject/galaxy/tar.gz/master
 - tar -zxvf master | tail
 - cd galaxy-central-master


# Configuring tools within Galaxy
# ===============================
#
# We setup a minimal tool_conf.xml and/or tool_conf.xml.sample file to
# get Galaxy to just test our tools, rather than via a (local) Galaxy
# Tool Shed.
#
# TODO - GALAXY_TEST_TOOL_CONF environment variable rather than symlink?
#
# We setup our tools under the Galaxy tool folder by using symlinks.
# TODO - Restructure this to auto-update in future when add folders?
#
# We setup our datatypes by adding blast.py to the Galaxy library, and
# adding the insert into lib/galaxy/datatypes/registry.py, and replacing
# the datatypes_conf.xml file.
#
# We setup our sample data in the Galaxy test-data folder by copying them
# (using symlinks might be faster?)
#
# We setup out sample *.loc files in the Galaxy tool-data folder by copying
# them (using symlinks might be faster?)
#
# We then want to use run.sh to setup all the sample files, fetch eggs etc,
# but not actually start running Galaxy. One way to do this is by calling
# "./run.sh --stop-daemon" but must override its error level 1 return value.
#

install:
 - cd ${TRAVIS_BUILD_DIR}/galaxy-central-master
 - export GALAXY_TEST_UPLOAD_ASYNC=false
 - export GALAXY_TEST_DB_TEMPLATE=https://github.com/jmchilton/galaxy-downloads/raw/master/db_gx_rev_0120.sqlite
 - rm -f tool_conf.xml
 - ln -s ${TRAVIS_BUILD_DIR}/.travis.tool_conf.xml tool_conf.xml
 - rm -f config/tool_conf.xml.sample
 - ln -s ${TRAVIS_BUILD_DIR}/.travis.tool_conf.xml config/tool_conf.xml.sample
 - rm -f config/shed_tool_data_table_conf.xml
 - ln -s ${TRAVIS_BUILD_DIR}/.travis.tool_data_table_conf.xml config/shed_tool_data_table_conf.xml
 - ln -s ${TRAVIS_BUILD_DIR}/tools/ncbi_blast_plus/ tools/ncbi_blast_plus
 - ln -s ${TRAVIS_BUILD_DIR}/tools/blastxml_to_top_descr/ tools/blastxml_to_top_descr
 - ln -s ${TRAVIS_BUILD_DIR}/tools/reciprocal_best_hits/ tools/reciprocal_best_hits
 - ln -s ${TRAVIS_BUILD_DIR}/tools/blast_rbh/ tools/blast_rbh
 - ln -s ${TRAVIS_BUILD_DIR}/tools/blast2go/ tools/blast2go
 - ln -s ${TRAVIS_BUILD_DIR}/datatypes/blast_datatypes/blast.py lib/galaxy/datatypes/blast.py
 - ln -s ${TRAVIS_BUILD_DIR}/.travis.datatypes_conf.xml datatypes_conf.xml
 - cp ${TRAVIS_BUILD_DIR}/test-data/* test-data/
 - cp ${TRAVIS_BUILD_DIR}/tool-data/* tool-data/
 - ./run.sh --stop-daemon || true
 - python scripts/fetch_eggs.py


# Testing tools in Galaxy
# =======================
#
# Having setup our Galaxy with a minimal tool_conf.xml / tool_conf.xml.sample
# we call run_functional_tests.sh to run just our tests (grouped under a
# common section "travis" in the XML file for this purpose).
#
# ./run_functional_tests.sh -sid Continuous-Integration-Travis
#
# calls:
#
# python ./scripts/functional_tests.py --with-nosehtml --html-report-file run_functional_tests.html -v `python tool_list.py Continuous-Integration-Travis`
#
# That gives an error sadly under Travis,
# functional_tests.py: error: no such option: --with-nosehtml
# And also,
# functional_tests.py: error: no such option: --html-report-file
# Perhaps Galaxy's nose egg isn't being fetched?

script:
 - python ./scripts/functional_tests.py -v `python tool_list.py Continuous-Integration-Travis`

#The email defaults are too talkative while we're getting Travis working nicely.
notifications:
  email: false
